spring:
  jpa:
    database: MYSQL
    show-sql: false
    hibernate:
      ddl-auto: none
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/siomari_db?useSSL=false
    username: root
    password: 
security:
  oauth2:
    resource:
      filter-order: 3 
